export const ProductsAction = {
    SET_PRODUCTS: `shop/Set_Products`,
    FECTCH_PRODUCTS_START: `shop/FECTCH_PRODUCTS_START`,
    FECTCH_PRODUCTS_SUCCESS: `shop/FECTCH_PRODUCTS_SUCCESS`,
    FECTCH_PRODUCTS_FAILURE: `shop/FECTCH_PRODUCTS_FAILURE`
}